apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-microservice
  template:
    metadata:
      labels:
        app: azure-microservice
    spec:
      containers:
      - name: azure-microservice
        image: hamzayyoussef/azuremicroservice:172
        ports:
        - containerPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: azure-microservice-service
spec:
  selector:
    app: azure-microservice
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
  type: LoadBalancer