apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-microservice
  labels:
    app: client-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-microservice
  template:
    metadata:
      labels:
        app: client-microservice
    spec:
      containers:
      - name: client-microservice
        image: hamzayyoussef/clientmicroservice:164
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: client-microservice-service
spec:
  type: LoadBalancer
  ports:
    - port: 9092
  selector:
    app: client-microservice