apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-microservice
  labels:
    app: license-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: license-microservice
  template:
    metadata:
      labels:
        app: license-microservice
    spec:
      containers:
      - name: license-microservice
        image: hamzayyoussef/licensemicroservice:171
        ports:
        - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: license-microservice-service
spec:
  type: LoadBalancer
  ports:
    - port: 9093
  selector:
    app: license-microservice