apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
  labels:
    app: user-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
      - name: user-microservice
        image: hamzayyoussef/usermicroservice:161
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice-service
spec:
  type: LoadBalancer
  ports:
    - port: 9091
      targetPort: 9091
  selector:
    app: user-microservice